export const FETCH_USER = 'FETCH_USER';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const AUTH_USER = 'AUTH_USER';
export const UNAUTH_USER = 'UNAUTH_USER';
export const MY_INTERVIEWS_TAB = 'MY_INTERVIEWS_TAB';
export const NEW_INTERVIEW_TAB = 'NEW_INTERVIEW_TAB';
export const FETCH_INTERVIEWS = 'FETCH_INTERVIEWS';